/* Client brand revision. Content stays local until approved for publication. */
module.exports = function revise(pages, {image, pageIntro}) {
  const companies = [
    ['Productions','production','Stories worth telling.','Film, documentary, web series, podcasts, digital content and original productions.','production',false],
    ['Events','events','Moments worth remembering.','Concerts, festivals, corporate events, weddings and private celebrations.','events',false],
    ['Luxury','luxury','Life, impeccably arranged.','Private concierge and lifestyle services, shaped around discretion, access and attention to detail.','travel',true],
    ['Digital','digital','Ideas, engineered.','Technology, applications and digital products designed around real-world needs.','hero',true],
    ['Experiences','experiences','The world, thoughtfully experienced.','Destination management, curated journeys and experiences across selected destinations.','landscape',true]
  ];
  const label = t => `<p class="eyebrow">${t}</p>`;
  const split = (tag,title,copy) => `<section class="brand-section container brand-split"><div class="reveal">${label(tag)}<h2 class="heading">${title}</h2></div><div class="brand-copy reveal">${copy}</div></section>`;
  const paragraph = t => `<p>${t}</p>`;
  const companyList = base => `<div class="company-list">${companies.map(c=>`<a class="company-row reveal" href="${base}${c[1]}/index.html"><span class="company-name">${c[0]}</span><span class="company-line">${c[2]}</span><span class="company-state">${c[5]?'Coming soon':'Explore'}</span></a>`).join('')}</div>`;
  const locations = `<section class="brand-locations container brand-section">${label('International by nature')}<h2 class="heading reveal">Wherever the project<br><em>takes us.</em></h2><div class="city-list"><span>London</span><span>Doha</span><span>Beirut</span></div><p class="body-copy">Local knowledge. International expertise. One team.</p></section>`;
  const process = (title, steps) => `<section class="brand-section container">${label('Our approach')}<h2 class="heading reveal">${title}</h2><ol class="brand-process">${steps.map(s=>`<li class="reveal">${s}</li>`).join('')}</ol></section>`;
  const home=pages.find(p=>p.active==='home');
  const heroEnd=home.body.indexOf('<div class="manifesto-strip"');
  home.body=home.body.slice(0,heroEnd)
    .replace('A collective vision. A world of possibility.','Otium Group')
    .replace('Many worlds.<br>One <em>vision.</em>','The art of making<br><em>things happen.</em>')
    .replace('Bringing people, ideas, and businesses together<br>to create what comes next.','We create stories, experiences and moments<br>that bring people together.')
    .replace('Explore our worlds','Our companies').replace('Discover Otium','About Otium')
    .replace(/<a class="hero-caption"[\s\S]*?<\/a>/,'<p class="hero-geography">London · Doha · Beirut · Worldwide</p>');
  home.body+=`<section class="brand-section container" id="introduction"><div class="brand-section-top reveal">${label('Our companies')}<h2 class="heading">One group.<br><em>Many disciplines.</em></h2><p class="body-copy">Otium is an international multidisciplinary group with expertise across production, events, entertainment, technology, luxury and destination experiences.</p></div>${companyList('')}</section>`;
  home.body+=split('Our people','Built around people.<br><em>Driven by ideas.</em>',paragraph('Our strength is our people: an international network of specialists, creatives, producers, strategists and operators who bring different perspectives to every project.')+paragraph('We believe the best work happens when expertise is shared, ideas are challenged and everyone takes ownership.')+'<a class="text-link" href="about/index.html">Meet Otium</a>');
  home.body+=`<section class="brand-band"><div class="container"><p>Multidisciplinary.</p><p>International.</p><p>Hands-on.</p><p>Human.</p></div></section>`;
  home.body+=process('From first idea<br>to <em>final delivery.</em>',['Develop','Produce','Coordinate','Execute','Deliver'])+locations;
  home.title='Otium Group — The art of making things happen.';
  home.description='An international multidisciplinary group across productions, events, luxury, digital and destination experiences. London, Doha, Beirut and worldwide.';

  const about=pages.find(p=>p.active==='about');
  about.body=pageIntro('About Otium','People. Ideas.<br><em>Execution.</em>','An international creative and experiential group bringing together people, ideas and capabilities to create work that moves, engages and endures.');
  about.body+=`<div class="brand-panorama">${image('../','hero','A sculptural opening onto the Mediterranean horizon','',true)}</div>`;
  about.body+=split('Who we are','Different perspectives.<br><em>One team.</em>',paragraph('A producer sees the story. An event specialist sees the audience. A strategist sees the opportunity. A technologist sees what is possible. An operator sees how to make it happen.')+paragraph('Otium brings together creative, production, operational and commercial expertise under one roof — allowing us to approach ambitious projects from every angle and deliver them from concept to completion.'));
  about.body+=split('Mission & vision','Ambitious ideas.<br><em>Exceptional realities.</em>',paragraph('Our mission is to bring together the right people, expertise and resources to create work that is meaningful, memorable and meticulously delivered.')+paragraph('Our vision is to build an international group recognised for the quality of its ideas, the strength of its people and the excellence of its execution.')+paragraph('We combine creativity with commercial thinking, imagination with discipline, and international perspective with local understanding.'));
  about.body+=split('Our people','Expertise, shared.',paragraph('Producers, directors, event professionals, project managers, strategists, creatives, technical specialists, marketers, communicators and hospitality professionals.')+paragraph('We assemble the right team for each project rather than forcing every project into the same mould.'));
  about.body+=`<section class="brand-section container brand-values">${label('Our philosophy')}<h2 class="heading reveal">Ideas with substance.<br><em>Care in the details.</em></h2><div class="values-grid">${[['Curiosity','We ask questions, explore possibilities and look beyond the obvious.'],['Craft','We care about the details because excellence lives in the details.'],['Collaboration','Different disciplines and perspectives make the work stronger.'],['Ownership','We take responsibility from the first conversation to final delivery.'],['Agility','Markets, audiences and projects change. We adapt.'],['Integrity','We build relationships for the long term.'],['Ambition','We are comfortable thinking bigger and travelling further.']].map(v=>`<article class="reveal"><h3>${v[0]}</h3><p>${v[1]}</p></article>`).join('')}</div></section>`+locations;
  const divisions=pages.find(p=>p.active==='divisions');
  divisions.title='Our Companies — Otium Group';
  divisions.description='Meet Otium Productions and Otium Events, with Luxury, Digital and Experiences taking shape.';
  divisions.body=pageIntro('Our companies','Distinct expertise.<br><em>A shared standard.</em>','Independent disciplines, brought together through creative thinking and hands-on execution.')+`<section class="container company-directory">${companies.map(c=>`<article class="company-feature reveal"><div>${label(c[5]?'Coming soon':'Otium Group')}<h2>Otium <em>${c[0]}</em></h2><h3>${c[2]}</h3><p class="body-copy">${c[3]}</p><a class="text-link" href="../${c[1]}/index.html">${c[5]?'Preview '+c[0]:'Explore '+c[0]}</a></div><a href="../${c[1]}/index.html" aria-label="Otium ${c[0]}">${image('../',c[4],`${c[0]} visual direction`)}</a></article>`).join('')}</section>`;

  const production=pages.find(p=>p.active==='production');
  const openingEnd=production.body.indexOf('</nav>')+6;
  const workStart=production.body.indexOf('<section class="work-section');
  const showreelStart=production.body.indexOf('<section class="showreel');
  const dialogStart=production.body.indexOf('<dialog');
  const gallery=production.body.slice(workStart,showreelStart);
  const dialog=production.body.slice(dialogStart);
  production.body=production.body.slice(0,openingEnd).replace('Ideas into<br><em>something real.</em>','Stories<br><em>worth telling.</em>').replace('Film, stories, and experiences.<br>A different perspective, beautifully brought to life.','Documentaries, web series, podcasts and original content. Stories with substance, style and purpose.');
  production.body+=split('Otium Productions','Stories that<br><em>stay with you.</em>',paragraph('Otium Productions is an international production company creating documentaries, web series, podcasts, digital content and original productions for audiences across markets and platforms.')+paragraph('From the first idea to the final frame, we bring together creative vision, editorial intelligence and hands-on production expertise.'));
  const formats=[['Documentary','Factual storytelling with cinematic ambition. Character-driven films and cultural, social, business and human-interest documentaries.'],['Web Series','Distinctive original episodic formats built for contemporary digital audiences.'],['Podcasts','Interview-led formats, documentary podcasts and original audio series. Conversations and ideas made to be heard.'],['Digital Content','Short-form, branded, editorial and social content, created with the same care as our larger productions.'],['Original Productions','Our own ideas, developed alongside creators, brands, broadcasters, platforms and organisations.']];
  production.body+=`<section class="brand-section container" id="capabilities">${label('What we produce')}<h2 class="heading reveal">Every story.<br><em>Its own format.</em></h2><div class="brand-accordions">${formats.map(f=>`<details class="reveal"><summary>${f[0]}<span aria-hidden="true">+</span></summary><p>${f[1]}</p></details>`).join('')}</div></section>`;
  production.body+=process('From concept<br>to <em>completion.</em>',['Development','Creative','Pre-production','Production','Post-production','Distribution']);
  production.body+=split('Creative minds. Production discipline.','International stories.<br><em>Local intelligence.</em>',paragraph('Our network spans Europe, the Middle East and beyond. We build productions around the people, locations and relationships that make each market unique.')+paragraph('We collaborate with creators and filmmakers, broadcasters and platforms, brands, agencies, cultural institutions, talent and production partners.'))+gallery+dialog;
  production.title='Otium Productions — Stories worth telling.';
  production.description='Documentaries, web series, podcasts, digital content and original productions. International perspective, editorial intelligence and hands-on production.';

  const events=pages.find(p=>p.file==='events/index.html');
  events.active='events';events.title='Otium Events — Moments worth remembering.';events.description='Concerts, festivals, corporate events, weddings and private celebrations. Creative thinking, meticulous planning and hands-on delivery.';
  events.body=`<section class="event-opening">${image('../','events','Concert audience beneath stage lights — illustrative imagery','',true)}<div class="container">${label('Otium Events')}<h1>Moments worth<br><em>remembering.</em></h1><p>From a stage full of possibility<br>to a celebration that feels entirely yours.</p><a class="pill solid" href="../contact/index.html?type=Events">Plan an event</a></div></section><nav class="production-jumps container" aria-label="Events sections"><a href="#event-types">Our events</a><a href="#event-capabilities">Capabilities</a><a href="../contact/index.html?type=Events">Start a conversation</a></nav>`;
  events.body+=split('Otium Events','Different scale.<br><em>Same attention.</em>',paragraph('We create, produce and deliver live experiences across entertainment, corporate, private and social events.')+paragraph('From concerts and festivals to intimate gatherings, we combine creative thinking, meticulous planning and hands-on execution. We think about the whole experience — and the details that make it work.'));
  events.body+=`<section class="brand-section container" id="event-types">${label('Live experiences')}<div class="event-types">${[['Live Entertainment','Big stages. Big audiences. Big moments.','Concerts, festivals, public events and cultural productions. Creative ambition supported by disciplined planning and on-site operations.'],['Corporate Events','Business, beautifully delivered.','Conferences, launches, galas, awards, brand activations and executive gatherings. Built around what your organisation wants to achieve.'],['Weddings & Private Celebrations','Your occasion. Your story.','From concept and venue to entertainment, styling, hospitality and on-the-day management, we take care of the moving parts.']].map(e=>`<article class="reveal"><h2>${e[0]}</h2><h3>${e[1]}</h3><p>${e[2]}</p></article>`).join('')}</div></section>`;
  events.body+=`<section class="brand-section container" id="event-capabilities">${label('Capabilities')}<h2 class="heading reveal">Every detail.<br><em>Considered.</em></h2><div class="brand-accordions">${[['Creative & planning','Concept, creative direction, venue sourcing, talent coordination and production management.'],['Technical & operations','Stage production, audio, lighting, visual systems, audience management, security and safety coordination, and on-site operations.'],['Audience & partnerships','Ticketing, sponsorship, marketing, communications, hospitality and VIP management.'],['Delivery & follow-through','Event delivery, team coordination and post-event management. Individual services or the complete event lifecycle.']].map(e=>`<details class="reveal"><summary>${e[0]}<span aria-hidden="true">+</span></summary><p>${e[1]}</p></details>`).join('')}</div></section>`+process('From first idea<br>to <em>final applause.</em>',['Concept','Strategy','Planning','Production','Delivery','Experience'])+locations;
  for(const c of companies.filter(c=>c[5]))pages.push({file:c[1]+'/index.html',base:'../',active:'divisions',title:`Otium ${c[0]} — ${c[2]}`,description:c[3]+' Coming soon.',hero:c[4],body:pageIntro('Otium '+c[0]+' / Coming soon',c[2],c[3])+`<div class="brand-panorama">${image('../',c[4],c[0]+' visual direction','',true)}</div>`+split('In development','A new Otium<br><em>chapter.</em>',paragraph('Further details will be shared as this company takes shape.')+`<a class="text-link" href="../contact/index.html?type=${c[0]}">Register your interest</a>`) });
  const travel=pages.find(p=>p.file==='travel/index.html');
  travel.body=pageIntro('Otium Experiences','A wider<br><em>world.</em>','Our travel and destination offering is taking shape as Otium Experiences.')+'<div class="container brand-section"><a class="pill solid" href="../experiences/index.html">Discover Otium Experiences</a></div>';
  travel.title='Otium Experiences — formerly Travel';travel.description='Discover the forthcoming Otium Experiences company.';
  const contact=pages.find(p=>p.active==='contact');
  contact.body=contact.body.replace('Good things begin<br>with <em>hello.</em>','Let’s make<br><em>it happen.</em>').replace('A possibility. A partnership. A project waiting to happen. We’d love to hear what you have in mind.','A brief, an idea, a script, an occasion. Tell us what you are imagining.').replace('Your next chapter','Start a conversation').replace('Let’s make<br>it <em>meaningful.</em>','The right people.<br><em>For your idea.</em>').replace('<option value="Production">A production project</option>',companies.map(c=>`<option value="${c[0]}">Otium ${c[0]}${c[5]?' — register interest':''}</option>`).join(''));
  contact.title='Contact Otium — Let’s make it happen.';
  return companies;
};
