/* Optional authoring utility. Generated HTML is ready to open or host as-is.
 * Run with Node only when changing shared markup; no npm or framework required.
 */
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const content = {window:{}};
vm.runInNewContext(fs.readFileSync(path.join(root,'data/projects.js'),'utf8'), content);
const { OTIUM_PROJECTS: projects, OTIUM_SERVICES: services } = content.window;
const arrow = '<span class="arrow" aria-hidden="true">↗</span>';
const esc = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function image(base,name,alt,cls='',eager=false,sizes='100vw') {
  return `<img ${cls ? `class="${cls}" ` : ''}src="${base}assets/images/${name}-1600.webp" srcset="${base}assets/images/${name}-800.webp 800w, ${base}assets/images/${name}-1600.webp 1600w" sizes="${sizes}" alt="${esc(alt)}" ${eager?'fetchpriority="high" loading="eager"':'loading="lazy"'} decoding="async" width="1600" height="1000">`;
}
function brand(base) { return `<a class="brand" href="${base}index.html" aria-label="Otium Group home"><span class="brand-mark" aria-hidden="true"><img src="${base}assets/images/otium-logo.webp" alt="" width="600" height="400"></span><span class="brand-name">OTIUM<small>GROUP</small></span></a>`; }
function header(base,active) {
  const links=[['Group','index.html','home'],['Production','production/index.html','production'],['Divisions','divisions/index.html','divisions'],['About','about/index.html','about']];
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header">${brand(base)}<nav class="desktop-nav" aria-label="Main navigation">${links.map(([label,href,key])=>`<a href="${base}${href}"${key===active?' aria-current="page"':''}>${label}</a>`).join('')}</nav><a class="pill header-contact" href="${base}contact/index.html"${active==='contact'?' aria-current="page"':''}>Let’s talk ${arrow}</a><button class="menu-toggle" aria-expanded="false" aria-controls="mobile-menu"><span class="menu-label">Menu</span><span class="menu-icon" aria-hidden="true"><i></i><i></i></span></button></header><div class="mobile-menu" id="mobile-menu" hidden><nav aria-label="Mobile navigation">${[...links,['Contact','contact/index.html','contact']].map(([label,href,key],i)=>`<a href="${base}${href}"${key===active?' aria-current="page"':''}>${label}<span>0${i+1}</span></a>`).join('')}</nav><p class="eyebrow">People. Ideas. Businesses.</p></div>`;
}
function footer(base,production=false) {
  return `<footer class="site-footer"><div class="container"><div class="footer-cta"><div><p class="eyebrow">${production?'Your next great idea starts here':'A conversation can change everything'}</p><h2>${production?'Have a project':'Let’s create'}<br>${production?'<em>in mind?</em>':'what comes <em>next.</em>'}</h2></div><a class="circle-button" href="${base}contact/index.html${production?'?type=Production':''}" aria-label="Start a conversation">${arrow}</a></div><div class="footer-middle"><div class="footer-brand">${brand(base)}<p>People. Ideas. Businesses.<br>A brighter tomorrow.</p></div><nav class="footer-nav" aria-label="Footer navigation"><h3>Explore</h3><a href="${base}index.html">The Group</a><a href="${base}about/index.html">About us</a><a href="${base}divisions/index.html">Our divisions</a><a href="${base}contact/index.html">Get in touch ${arrow}</a></nav><nav class="footer-nav" aria-label="Our divisions"><h3>Our worlds</h3><a href="${base}production/index.html">Otium Production</a><a href="${base}travel/index.html">Otium Travel <span>Coming soon</span></a><a href="${base}events/index.html">Otium Events <span>Coming soon</span></a></nav></div><div class="footer-bottom"><span>© <span data-year>2026</span> Otium Group. All rights reserved.</span><span>Different worlds. One vision.</span><a href="#top">Back to top <span class="arrow" aria-hidden="true">↑</span></a></div><div class="footer-wordmark" aria-hidden="true">OTIUM</div></div></footer>`;
}
function shell({base='',active,title,description,body,extra='',hero='hero'}) {
  return `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#171a17"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:site_name" content="Otium Group"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:image" content="${base}assets/images/${hero}-1600.webp"><meta name="twitter:card" content="summary_large_image"><link rel="icon" type="image/svg+xml" href="${base}assets/favicon.svg"><link rel="preload" href="${base}assets/fonts/dm-sans-400.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="${base}assets/fonts/instrument-serif-italic.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="${base}style.css"><script defer src="${base}data/site.js"></script><script defer src="${base}js/main.js"></script>${extra}</head><body id="top">${header(base,active)}<main id="main" tabindex="-1">${body}</main>${footer(base,active==='production')}</body></html>`;
}
const values = `<ol class="value-list"><li class="reveal"><span class="number">01</span><div><h3>Creativity, with purpose.</h3><p>Ideas that move people and open possibilities.</p></div></li><li class="reveal" style="--delay:.08s"><span class="number">02</span><div><h3>Precision in every detail.</h3><p>Thoughtful decisions. Considered execution.</p></div></li><li class="reveal" style="--delay:.16s"><span class="number">03</span><div><h3>A shared ambition.</h3><p>Different perspectives. One collective vision.</p></div></li></ol>`;
function philosophy(base) { return `<section class="philosophy section-pad"><div class="container philosophy-grid"><div class="reveal" data-reveal="left"><p class="eyebrow">The way we see it</p><h2 class="heading">Extraordinary<br>begins with<br><em>intention.</em></h2></div>${values}</div></section>`; }
function pageIntro(label,heading,copy,aside='') { return `<section class="page-intro"><div class="container"><p class="eyebrow">${label}</p><h1>${heading}</h1><div class="page-intro-bottom"><p class="body-copy">${copy}</p>${aside?`<p class="eyebrow no-dot">${aside}</p>`:''}</div></div></section>`; }
const divisionItems = [
  {name:'Production',slug:'production',image:'production',alt:'A clapperboard held up on an outdoor film set',status:'Explore the division',description:'Where ideas find their expression. A world of film, storytelling, and creative possibility.'},
  {name:'Travel',slug:'travel',image:'travel',alt:'Sunlit Mediterranean villa beside a swimming pool',status:'Coming soon',description:'A new perspective on places, people, and the journeys that connect them. Our next chapter is taking shape.'},
  {name:'Events',slug:'events',image:'events',alt:'An audience coming together beneath concert lights',status:'Coming soon',description:'Moments that bring people together. A new world of shared experiences is on the horizon.'}
];

const home = `<section class="hero group-hero" aria-labelledby="hero-title"><div class="hero-media">${image('','hero','Sculptural stone portal opening onto a golden Mediterranean horizon','',true)}</div><div class="container hero-content"><p class="eyebrow">A collective vision. A world of possibility.</p><h1 class="hero-title" id="hero-title">Many worlds.<br>One <em>vision.</em></h1><p class="hero-description">Bringing people, ideas, and businesses together<br>to create what comes next.</p><div class="hero-actions"><a class="pill solid" href="divisions/index.html">Explore our worlds ${arrow}</a><a class="hero-secondary" href="about/index.html">Discover Otium <span class="arrow" aria-hidden="true">↗</span></a></div></div><div class="hero-bottom"><a class="scroll-cue" href="#introduction"><span class="circle-button"><span class="arrow" aria-hidden="true">↓</span></span>Scroll to discover</a><a class="hero-caption" href="production/index.html">${image('','production','','',false,'100px')}<div><small>In focus / Otium Production</small><span>Ideas into impact.</span></div>${arrow}</a></div></section><div class="manifesto-strip" aria-label="People. Ideas. Businesses. A brighter tomorrow."><span>PEOPLE</span><i aria-hidden="true"></i><span>IDEAS</span><i aria-hidden="true"></i><span>BUSINESSES</span><i aria-hidden="true"></i><span>A BRIGHTER TOMORROW</span></div>
<section class="section-pad" id="introduction"><div class="container intro-grid"><p class="eyebrow reveal">01 / The Otium perspective</p><div><h2 class="heading reveal">Different expertise.<br>Connected by <em>possibility.</em></h2><div class="intro-bottom"><p class="body-copy reveal">Otium brings together distinct worlds with a shared outlook: to turn thoughtful ideas into meaningful experiences. Each division has its own perspective. Together, they open new possibilities.</p><a class="text-link reveal" href="about/index.html">Meet Otium Group ${arrow}</a></div></div></div></section>
<section class="divisions-section container" aria-labelledby="worlds-title"><div class="section-top"><div class="reveal"><p class="eyebrow">02 / Our worlds</p><h2 class="heading" id="worlds-title">Distinct worlds.<br><em>Shared ambition.</em></h2></div><p class="body-copy reveal" data-reveal="right">One group. Independent perspectives.<br>Discover the divisions shaping<br>the Otium story.</p></div><div class="division-panels">${divisionItems.map((d,i)=>`<a class="division-panel reveal" data-reveal="scale" style="--delay:${i*.08}s" href="${d.slug}/index.html" aria-label="Otium ${d.name}${i?' — coming soon':''}">${image('',d.image,d.alt,'',false,'(max-width: 600px) 100vw, 45vw')}<div class="panel-top"><span>0${i+1}</span><span class="status">${i?'Coming soon':'Explore the division'}</span></div><div class="panel-bottom"><div><p>Otium</p><h3>${d.name}</h3></div><span class="circle-button">${arrow}</span></div></a>`).join('')}</div><div class="divisions-bottom"><p>A collective of possibilities, continually evolving.</p><a class="text-link" href="divisions/index.html">The bigger picture ${arrow}</a></div></section>
<section class="production-feature">${image('','production','A clapperboard on a sunlit outdoor film location')}<div class="container"><div class="reveal" data-reveal="left"><p class="eyebrow">03 / In focus — Otium Production</p><h2>Stories move us.<br>We <em>make them.</em></h2><p class="body-copy">An idea. A different perspective. A story waiting to be told. Step into the creative world of Otium Production.</p><a class="pill solid" href="production/index.html">Enter Otium Production ${arrow}</a></div></div><p class="feature-side"><span>01</span> Our creative world</p></section>
${philosophy('')}<div class="marquee" aria-hidden="true"><div class="marquee-track"><span>People. Ideas.</span><span class="marquee-star">✳</span><em>Possibilities.</em><span class="marquee-star">✳</span><span>People. Ideas.</span></div></div>`;

const about = `${pageIntro('Inside Otium Group','A wider<br><em>perspective.</em>','People, ideas, and businesses. Connected through a shared belief in what comes next.','Different worlds. One vision.')}<div class="about-image">${image('../','hero','An architectural opening framing the sea and a warm horizon','',true)}</div><section class="section-pad container about-story"><div class="reveal" data-reveal="left"><p class="eyebrow">The idea behind Otium</p><h2 class="heading">Better,<br><em>together.</em></h2></div><div class="story-copy reveal" data-reveal="right"><p class="body-copy">Otium Group is a home for distinct businesses and a shared way of thinking. We see opportunity in the connections between disciplines, between people, and between an idea and its execution.</p><p class="body-copy">Our divisions have room to develop their own expertise and identity. What brings them together is an intention to create considered, meaningful experiences.</p><p class="body-copy">Production is the first chapter of our digital story. More worlds are taking shape.</p><a class="text-link" href="../divisions/index.html">Explore our divisions ${arrow}</a></div></section><section class="statement"><div class="container reveal"><p class="eyebrow">Our outlook</p><h2>To bring possibility into focus.<br>And give good ideas<br><em>somewhere to go.</em></h2></div></section>${philosophy('../')}`;

const divisions = `${pageIntro('The Otium collective','One group.<br><em>Many worlds.</em>','Individual expertise. Shared possibility. Explore the worlds that make up Otium.','01 active division / More to come')}<section class="container division-list" aria-label="Otium divisions">${divisionItems.map((d,i)=>`<article class="division-row"><div class="division-row-copy reveal" data-reveal="left"><p class="eyebrow">0${i+1} / ${i?'On the horizon':'The creative division'}</p><h2>Otium <em>${d.name}.</em></h2><p class="body-copy">${d.description}</p><a class="text-link" href="../${d.slug}/index.html">${i?'Discover what’s next':'Explore Production'} ${arrow}</a></div><a class="division-row-image reveal" data-reveal="scale" href="../${d.slug}/index.html" aria-label="Discover Otium ${d.name}">${image('../',d.image,d.alt,'',false,'(max-width: 600px) 100vw, 55vw')}</a></article>`).join('')}<p class="division-note">Travel and Events are preview destinations. Further details will be announced as each division takes shape.</p></section>`;

const slideData = [
  {image:'production',alt:'Hands holding a clapperboard on a desert film location',title:'Every frame, a possibility.',caption:'Film & creative production'},
  {image:'events',alt:'Crowd and stage lights at a live concert',title:'Culture, in focus.',caption:'Documentary & digital storytelling'},
  {image:'travel',alt:'Architectural villa beside a sunlit swimming pool',title:'See it differently.',caption:'Commercial & branded content'}
];
const production = `<section class="hero production-hero" aria-label="Otium Production introduction slideshow" aria-roledescription="carousel"><div class="hero-slides">${slideData.map((s,i)=>`<div class="hero-slide ${i===0?'active':''}" data-title="${s.title}" data-caption="${s.caption}" aria-hidden="${i!==0}" role="group" aria-roledescription="slide" aria-label="${i+1} of ${slideData.length}">${image('../',s.image,s.alt,'',i===0)}</div>`).join('')}</div><div class="container hero-content"><p class="eyebrow">Otium Production / A division of Otium Group</p><h1 class="hero-title">Beyond<br>the <span class="serif">ordinary.</span></h1><div class="hero-actions"><a class="pill solid" href="#work">Explore our creative world ${arrow}</a><a class="hero-secondary" href="../contact/index.html?type=Production">Start a project ${arrow}</a></div></div><div class="hero-bottom"><div class="slider-bottom"><p class="slide-description"><strong data-slide-title>${slideData[0].title}</strong><span data-slide-caption>${slideData[0].caption}</span></p><div class="slider-controls"><p class="slide-count"><b data-current-slide>01</b> <span>/ ${String(slideData.length).padStart(2,'0')}</span></p><div class="slider-progress" aria-hidden="true"></div><button class="pause-slider" aria-label="Pause slideshow" aria-pressed="false">Ⅱ</button><button class="circle-button" data-slide-prev aria-label="Previous slide"><span class="arrow" aria-hidden="true">←</span></button><button class="circle-button" data-slide-next aria-label="Next slide"><span class="arrow" aria-hidden="true">→</span></button></div></div></div></section>
<section class="section-pad production-intro"><div class="container intro-grid"><p class="eyebrow reveal">01 / The creative perspective</p><div><h2 class="heading reveal">An idea is only<br><em>the beginning.</em></h2><div class="intro-bottom"><p class="body-copy reveal">Production is how a thought becomes something you can see, hear, and feel. We believe the best stories begin with a different perspective — and come to life through every considered detail.</p><a class="text-link reveal" href="../contact/index.html?type=Production">Let’s make something ${arrow}</a></div></div></div></section>
<section class="container section-pad services-section" aria-label="Production capabilities"><div class="services-head"><p class="eyebrow">02 / Creative possibilities</p><p>Our proposed capabilities. Details to follow.</p></div><div class="service-list">${services.map((s,i)=>`<details class="service-item reveal"><summary><span class="number">0${i+1}</span><h3>${esc(s.title)}</h3><span class="service-plus" aria-hidden="true">+</span></summary><p>${esc(s.description)}</p></details>`).join('')}</div></section>
<section class="work-section section-pad" id="work"><div class="container"><div class="work-top"><div class="reveal"><p class="eyebrow">03 / A look at what’s possible</p><h2 class="heading">Creative<br><em>perspectives.</em></h2></div><p class="body-copy reveal">A visual preview of our portfolio direction. Illustrative imagery is shown here while the first approved Otium projects are prepared.</p></div><div class="filter-bar" role="group" aria-label="Filter portfolio">${['All','Film','Commercial','Events','Branded content'].map((cat,i)=>`<button class="filter-button" data-filter="${cat}" aria-pressed="${i===0}">${cat}<span>${i===0?projects.length:projects.filter(p=>p.category===cat).length}</span></button>`).join('')}</div><p class="sr-only" data-filter-status role="status" aria-live="polite">${projects.length} projects shown.</p><div class="project-grid">${projects.map(p=>`<article class="project-card reveal" data-category="${esc(p.category)}"><button class="project-open" data-project="${p.id}" aria-label="View ${esc(p.title)} — illustrative concept"><span class="project-image">${image('../',p.image,p.alt,'',false,'(max-width: 600px) 100vw, 50vw')}<span class="project-view" aria-hidden="true">VIEW CONCEPT ↗</span></span></button><div class="project-meta"><div><h3>${esc(p.title)}</h3><p>${esc(p.category)} / Visual concept</p></div>${arrow}</div></article>`).join('')}</div><p class="project-empty" hidden>No projects in this category yet.</p><noscript><p>These are illustrative concepts. Project previews and filters require JavaScript.</p></noscript></div></section>
<section class="showreel">${image('../','events','An audience gathered in front of a dramatically lit stage')}<p class="eyebrow">Otium Production / The showreel</p><h2>Our world.<br><em>In motion.</em></h2><button class="play-reel" data-showreel><span class="circle-button"><span class="play-icon" aria-hidden="true"></span></span><span>Discover the showreel</span></button><p class="reel-note">The official Otium showreel is coming soon.</p></section>
<dialog class="lightbox" aria-labelledby="lightbox-title"><div class="lightbox-top"><div><h2 id="lightbox-title">Project preview</h2><p data-lightbox-category></p></div><button class="close-lightbox" aria-label="Close project preview" autofocus>×</button></div><div class="lightbox-media"></div><p class="lightbox-description"></p></dialog>`;

function coming(name,imageName,statement,description) { return `<section class="hero coming-hero"><div class="hero-media">${image('../',imageName,`${name==='Travel'?'A sunlit villa opening onto a quiet pool':'A sea of people gathered under stage lights'}`,'',true)}</div><div class="container hero-content"><p class="eyebrow">Otium ${name} / A new chapter is coming</p><h1 class="hero-title">${statement}</h1><p class="hero-description">${description}</p><div class="hero-actions"><a class="pill solid" href="../index.html">Return to Otium Group ${arrow}</a></div></div><div class="hero-bottom"><p class="eyebrow">Coming soon</p><p class="coming-note">Part of the Otium collective.<br>Different worlds. One vision.</p></div></section>`; }

const contact = `${pageIntro('Start a conversation','Good things begin<br>with <em>hello.</em>','A possibility. A partnership. A project waiting to happen. We’d love to hear what you have in mind.')}<section class="container contact-layout"><aside class="contact-aside"><p class="eyebrow">Your next chapter</p><h2 class="heading">Let’s make<br>it <em>meaningful.</em></h2><p class="body-copy">Tell us a little about yourself and your idea. Whether the vision is fully formed or just a first thought, this is a place to begin.</p><div class="contact-details" data-contact-details></div><div class="contact-brand-art"><img src="../assets/images/otium-logo.webp" alt="Otium Group — people, ideas, businesses, a brighter tomorrow" loading="lazy" width="600" height="400"></div></aside><form class="inquiry-form"><div class="form-grid"><div class="field"><label for="name">Your name <span>*</span></label><input id="name" name="name" autocomplete="name" placeholder="Full name" required maxlength="120"></div><div class="field"><label for="company">Company <span>(optional)</span></label><input id="company" name="company" autocomplete="organization" placeholder="Company or organisation" maxlength="160"></div><div class="field"><label for="email">Email address <span>*</span></label><input id="email" name="email" type="email" autocomplete="email" placeholder="you@company.com" required maxlength="254"></div><div class="field"><label for="phone">Phone number <span>(optional)</span></label><input id="phone" name="phone" type="tel" autocomplete="tel" placeholder="Include country code" maxlength="40"></div><div class="field full"><label for="type">What brings you here? <span>*</span></label><select id="type" name="type" required><option value="" disabled selected>Select an inquiry type</option><option value="Production">A production project</option><option value="Partnership">A potential partnership</option><option value="General">A general conversation</option></select></div><div class="field full"><label for="message">Tell us about your idea <span>*</span></label><textarea id="message" name="message" placeholder="The idea, the ambition, the possibilities…" required minlength="10" maxlength="5000"></textarea></div></div><div class="form-footer"><p>Fields marked * are required.<br>Your idea stays yours.</p><button class="pill dark" type="submit"><span>Prepare inquiry</span>${arrow}</button></div><p class="form-notice">Prepare and save your project brief. Direct inquiries will open when our contact details are confirmed.</p><div class="form-result" role="status" aria-live="polite" tabindex="-1" hidden></div><noscript><p class="form-notice">Please enable JavaScript to prepare an inquiry. No information is sent without an approved inquiry service.</p></noscript></form></section>`;

const pages = [
  {file:'index.html',active:'home',title:'Otium Group — Many worlds. One vision.',description:'Discover Otium Group. People, ideas, and businesses brought together through Production, Travel, Events, and a shared vision of what comes next.',body:home},
  {file:'about/index.html',base:'../',active:'about',title:'Our Perspective — Otium Group',description:'A home for distinct businesses and a shared way of thinking. Discover the idea, outlook, and values behind Otium Group.',body:about},
  {file:'divisions/index.html',base:'../',active:'divisions',title:'Our Worlds — Otium Group',description:'Discover the Otium collective: explore Otium Production and preview the forthcoming Travel and Events divisions.',body:divisions},
  {file:'production/index.html',base:'../',active:'production',title:'Otium Production — Beyond the ordinary.',description:'Step into the creative world of Otium Production. Explore our visual direction, production possibilities, and future film portfolio.',body:production,hero:'production',extra:'<script defer src="../data/projects.js"></script><script defer src="../js/production.js"></script>'},
  {file:'travel/index.html',base:'../',active:'divisions',title:'Otium Travel — A new perspective. Coming soon.',description:'A new world of journeys is taking shape. Discover the coming-soon Otium Travel division.',body:coming('Travel','travel','Beyond<br><em>boundaries.</em>','A different way to see the world.<br>The next Otium journey is taking shape.'),hero:'travel'},
  {file:'events/index.html',base:'../',active:'divisions',title:'Otium Events — Moments that matter. Coming soon.',description:'A new world of shared experiences is on the horizon. Otium Events is coming soon.',body:coming('Events','events','Made to<br><em>be felt.</em>','Some moments stay with you.<br>A new world of Otium experiences is on its way.'),hero:'events'},
  {file:'contact/index.html',base:'../',active:'contact',title:'Start a Conversation — Otium Group',description:'A project, a possibility, a partnership. Tell Otium Group what you have in mind and prepare your project inquiry.',body:contact,extra:'<script defer src="../js/contact.js"></script>'}
];
// Approved editorial cleanup shared by every generated page.
function simplifyPresentation(html, page) {
  if (page.active === 'home') {
    html = html.replace(philosophy(''), '');
    html = html.replace(/<div class="marquee" aria-hidden="true">[\s\S]*?<\/div><\/div>/, '');
  }
  return html
    .replace(/<span class="circle-button"><span class="arrow" aria-hidden="true">↓<\/span><\/span>/g, '')
    .replace(/(<a class="circle-button" href="[^"]+" aria-label="Start a conversation">)[\s\S]*?<\/a>/g, (_, opening) => opening.replace('circle-button', 'text-link footer-contact-link') + 'Contact us</a>')
    .replace(/<span class="circle-button"><span class="arrow" aria-hidden="true">↗<\/span><\/span>/g, '')
    .replace(/<span class="arrow" aria-hidden="true">↗<\/span>/g, '')
    .replace(/ ↗/g, '')
    .replace(/(<p class="eyebrow[^"]*">)0\d \/ /g, '$1')
    .replace(/(<nav aria-label="Mobile navigation">[\s\S]*?<\/nav>)/g, nav => nav.replace(/<span>0\d<\/span>/g, ''))
    .replace(/<span class="number">0\d<\/span>/g, '')
    .replace(/(<div class="panel-top">)<span>0\d<\/span>/g, '$1')
    .replace(/<span>01<\/span> Our creative world/g, 'Our creative world')
    .replace(/Our worlds/g, 'Our divisions')
    .replace(/Explore our worlds/g, 'Explore our divisions')
    .replace('Creative<br><em>perspectives.</em>', 'Portfolio')
    .replace('Good things begin<br>with <em>hello.</em>', 'Contact <em>Otium.</em>')
    .replace('<p>A collective of possibilities, continually evolving.</p>', '')
    .replace('<p class="eyebrow">A conversation can change everything</p>', '')
    .replace('<p class="eyebrow">Your next great idea starts here</p>', '');
}
for (const page of pages) {
  if (process.argv.includes('--production-only') && page.active !== 'production') continue;
  if (process.argv.includes('--home-only') && page.active !== 'home') continue;
  if (page.active === 'production') {
    page.extra += '<link rel="stylesheet" href="../production.css">';
    const oldHeroEnd = page.body.indexOf('</section>') + '</section>'.length;
    const opener = `<section class="production-opening container"><div class="production-opening-copy"><p class="eyebrow">Otium Production</p><h1>Ideas into<br><em>something real.</em></h1><p class="body-copy">Film, stories, and experiences.<br>A different perspective, beautifully brought to life.</p><a class="text-link" href="../contact/index.html?type=Production">Start a project ${arrow}</a></div><div class="production-hero production-gallery" aria-label="Creative direction slideshow" aria-roledescription="carousel"><div class="production-gallery-window"><div class="hero-slides">${slideData.map((s,i)=>`<div class="hero-slide ${i===0?'active':''}" data-title="${esc(s.title)}" data-caption="${esc(s.caption)}" aria-hidden="${i!==0}" role="group" aria-roledescription="slide" aria-label="${i+1} of ${slideData.length}">${image('../',s.image,s.alt,'',i===0,'(max-width:800px) 100vw, 60vw')}</div>`).join('')}</div><span class="gallery-label">A glimpse of our world</span></div><div class="gallery-footer"><p class="slide-description"><strong data-slide-title>${slideData[0].title}</strong><span data-slide-caption>${slideData[0].caption}</span></p><div class="slider-controls"><span class="slide-count"><b data-current-slide>01</b> <span>/ ${String(slideData.length).padStart(2,'0')}</span></span><div class="slider-progress" aria-hidden="true"></div><button class="pause-slider" aria-label="Pause slideshow" aria-pressed="false">Ⅱ</button><button class="circle-button" data-slide-prev aria-label="Previous slide">←</button><button class="circle-button" data-slide-next aria-label="Next slide">→</button></div></div></div></section><nav class="production-jumps container" aria-label="Production page sections"><span>Explore Production</span><a href="#work">Visual portfolio ${arrow}</a><a href="#capabilities">Capabilities ${arrow}</a><a href="../contact/index.html?type=Production">Get in touch ${arrow}</a></nav>`;
    page.body = opener + page.body.slice(oldHeroEnd);
    page.body = page.body.replace('class="container section-pad services-section"', 'id="capabilities" class="container section-pad services-section"');
  }
  if (page.active === 'home') {
    page.extra = '<link rel="stylesheet" href="hero.css"><script defer src="js/hero.js"></script>';
    const poster = '<picture><source media="(max-width:600px)" srcset="frames/mobile/frame_0001.jpg"><img src="frames/frame_0001.jpg" alt="A golden stone portal opening onto a Mediterranean sunset" width="1280" height="720" fetchpriority="high"></picture><canvas class="hero-canvas" aria-hidden="true"></canvas>';
    page.body = '<div class="home-scroll">' + page.body
      .replace(image('','hero','Sculptural stone portal opening onto a golden Mediterranean horizon','',true), poster)
      .replace('</section><div class="manifesto-strip"', '<div class="hero-progress" aria-hidden="true"></div></section></div><div class="manifesto-strip"');
  }
}
const companies = require('./client-pages.cjs')(pages, {image, pageIntro});
for (const page of pages) {
  if (process.argv.includes('--home-only') && page.active !== 'home') continue;
  if (process.argv.includes('--production-only') && page.active !== 'production') continue;
  page.extra = (page.extra || '') + `<link rel="stylesheet" href="${page.base || ''}brand.css">`;
  if (page.active === 'production') require('./production-portfolio.cjs')(page, image);
  let html = simplifyPresentation(shell(page), page)
    .replace(/Otium Production\b/g, 'Otium Productions')
    .replace(/>Production<\/a>/g, '>Productions</a>')
    .replace(/>Divisions<\/a>/g, '>Companies</a>')
    .replace(/Our divisions/g, 'Our companies')
    .replace(/\?type=Production\b/g, '?type=Productions')
    .replace(/Different worlds\. One vision\./g, 'The art of making things happen.')
    .replace(/People\. Ideas\. Businesses\.<br>A brighter tomorrow\./g, 'London · Doha · Beirut<br>International by nature.')
    .replace(/<nav class="footer-nav" aria-label="Our companies">[\s\S]*?<\/nav>/, `<nav class="footer-nav" aria-label="Our companies"><h3>Our companies</h3>${companies.map(c=>`<a href="${page.base || ''}${c[1]}/index.html">Otium ${c[0]}${c[5]?'<span>Coming soon</span>':''}</a>`).join('')}</nav>`);
  html = html.replace('Let’s create<br>what comes <em>next.</em>', 'Let’s create something<br><em>worth remembering.</em>')
    .replace('Have a project<br><em>in mind?</em>', 'Let’s tell<br><em>a story.</em>');
  // Events is now an active destination in both navigation layouts.
  html = html.replace(/(<a href="(?:\.\.\/)?divisions\/index.html"[^>]*>Companies<\/a>)/g, `<a href="${page.base || ''}events/index.html"${page.active === 'events'?' aria-current="page"':''}>Events</a>$1`);
  fs.mkdirSync(path.dirname(path.join(root,page.file)),{recursive:true});
  fs.writeFileSync(path.join(root,page.file),html);
  console.log(`Wrote ${page.file}`);
}
