// Arabic interface labels for the existing Media Chrome controls inside Mux Player.
export const Ar = {
  'Start airplay':'بدء البث عبر AirPlay','Stop airplay':'إيقاف البث عبر AirPlay',
  'Audio':'الصوت','Captions':'الترجمة النصية','Enable captions':'إظهار الترجمة النصية','Disable captions':'إخفاء الترجمة النصية',
  'Start casting':'بدء البث إلى جهاز','Stop casting':'إيقاف البث إلى الجهاز',
  'Enter fullscreen mode':'عرض بملء الشاشة','Exit fullscreen mode':'الخروج من ملء الشاشة',
  'Mute':'كتم الصوت','Unmute':'تشغيل الصوت','Loop':'تكرار',
  'Enter picture in picture mode':'تفعيل صورة داخل صورة','Exit picture in picture mode':'إغلاق صورة داخل صورة',
  'Play':'تشغيل','Pause':'إيقاف مؤقت','Playback rate':'سرعة التشغيل','Playback rate {playbackRate}':'سرعة التشغيل {playbackRate}',
  'Quality':'الجودة','Seek backward':'رجوع','Seek forward':'تقديم','Settings':'الإعدادات','Auto':'تلقائي',
  'audio player':'مشغّل صوت','video player':'مشغّل فيديو','volume':'مستوى الصوت','seek':'موضع التشغيل',
  'closed captions':'الترجمة النصية','current playback rate':'سرعة التشغيل الحالية','playback time':'وقت التشغيل',
  'media loading':'جارٍ تحميل الوسائط','settings':'الإعدادات','audio tracks':'المسارات الصوتية','quality':'الجودة',
  'play':'تشغيل','pause':'إيقاف مؤقت','mute':'كتم الصوت','unmute':'تشغيل الصوت','chapter: {chapterName}':'الفصل: {chapterName}',
  'live':'مباشر','Off':'إيقاف','start airplay':'بدء البث عبر AirPlay','stop airplay':'إيقاف البث عبر AirPlay',
  'start casting':'بدء البث إلى جهاز','stop casting':'إيقاف البث إلى الجهاز',
  'enter fullscreen mode':'عرض بملء الشاشة','exit fullscreen mode':'الخروج من ملء الشاشة',
  'enter picture in picture mode':'تفعيل صورة داخل صورة','exit picture in picture mode':'إغلاق صورة داخل صورة',
  'seek to live':'الانتقال إلى البث المباشر','playing live':'يُعرض مباشرة',
  'seek back {seekOffset} seconds':'الرجوع {seekOffset} ثانية','seek forward {seekOffset} seconds':'التقديم {seekOffset} ثانية',
  'Network Error':'خطأ في الشبكة','Decode Error':'خطأ في فك الترميز','Source Not Supported':'المصدر غير مدعوم','Encryption Error':'خطأ في التشفير',
  'A network error caused the media download to fail.':'تعذّر تحميل الوسائط بسبب خطأ في الشبكة.',
  'A media error caused playback to be aborted. The media could be corrupt or your browser does not support this format.':'توقّف التشغيل بسبب خطأ في الوسائط. قد يكون الملف تالفًا أو قد لا يدعم متصفحك هذه الصيغة.',
  'An unsupported error occurred. The server or network failed, or your browser does not support this format.':'تعذّر التشغيل بسبب مشكلة في الخادم أو الشبكة، أو لأن متصفحك لا يدعم هذه الصيغة.',
  'The media is encrypted and there are no keys to decrypt it.':'الوسائط مشفّرة ولا تتوفر مفاتيح لفك تشفيرها.',
  'hour':'ساعة','hours':'ساعات','minute':'دقيقة','minutes':'دقائق','second':'ثانية','seconds':'ثوانٍ',
  '{time} remaining':'الوقت المتبقي: {time}','{currentTime} of {totalTime}':'{currentTime} من {totalTime}',
  'video not loaded, unknown time.':'لم يُحمّل الفيديو، والمدة غير معروفة.'
};
